[[constraint]]
  name = "github.com/splitio/go-split-commons"
  version = "=2.1.0"

[[constraint]]
  name = "github.com/splitio/go-toolkit"
  version = "=2.3.0"

[prune]
  go-tests = true
  unused-packages = true
